### ISSUE TITLE
Infinite "Saving blobs..." For download iOS beta blob

### ISSUE THREAD

**Issue by Jonesy-A9** [airsquared/blobsaver#219]
**Describe the bug**
The message box "Saving blobs..." running at the infinite when try to download iOS beta blob, but for normal release iOS blobs, it's works perfectly.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/62351492/99670877-84a4dc80-2a71-11eb-9fec-3d2ce862e26b.PNG)

**Desktop:**
 - OS Version: Windows 10 (20H2)
 - iOS Device: iOS 14.2 / iOS 14.3 beta 2

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
tsschecker = C:\Program Files\blobsaver\lib\tsschecker.exe
Extracting build manifest from https://updates.cdn-apple.com/2020WinterSeed/fullrestores/001-80698/B172DB41-6CEE-4DF0-9D85-FD877F6EA324/iPhone_5.5_P3_14.3_18C5044f_Restore.ipsw
Exception in thread "Thread-6" java.lang.Error: Invalid memory access
at com.airsquared.blobsaver.Shared$Libfragmentzip.fragmentzip_download_file(Native Method)
at com.airsquared.blobsaver.Shared$Libfragmentzip.downloadFile(Shared.java:291)
at com.airsquared.blobsaver.Shared.extractBuildManifest(Shared.java:272)
at com.airsquared.blobsaver.TSSChecker.run(TSSChecker.java:165)
at com.airsquared.blobsaver.TSSChecker.runImpl(TSSChecker.java:119)
at com.airsquared.blobsaver.TSSChecker.lambda$run$0(TSSChecker.java:47)
at java.lang.Thread.run(Unknown Source) 

```

**Comment by airsquared** [comment]
If you are still having this issue, please try the beta in #242.
