### ISSUE TITLE
Fall back on librecovery-1.0.so if libirecovery.so not found

### ISSUE THREAD

**Issue by mmhobi7** [airsquared/blobsaver#278]
**Describe the bug**
Blobsaver crashes when pulling APNounce from device. This is due to irecovery.so not being found (by tsschecker I presume) 
Can be fixed with:
`$ sudo ln -s /usr/lib/x86_64-linux-gnu/libirecovery-1.0.so.3.0.0 /usr/lib/x86_64-linux-gnu/libirecovery.so`

libirecovery-dev (https://packages.ubuntu.com/hirsute/amd64/libirecovery-1.0-dev/filelist) creates the symlink to:
/usr/lib/x86_64-linux-gnu/libirecovery-1.0.so

I'd recommend checking that libirecovery and libimobiledevice are found at app launch 

**Desktop:**
 - OS Version: Ubuntu 21.04
 - iOS Device: iPhone13,4

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver (v 3.0 downloaded today as of this post)
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
➜  ~ /opt/blobsaver/bin/blobsaver
Read in normal mode: 71bd1cd0c62f4058038a4255432c7273ca633ce25a83a67226063aeb487190de
java.lang.UnsatisfiedLinkError: Unable to load library 'irecovery':
libirecovery.so: cannot open shared object file: No such file or directory
libirecovery.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libirecovery.so) not found in resource path ()
	at com.sun.jna@5.7.0/com.sun.jna.NativeLibrary.loadLibrary(Unknown Source)
	at com.sun.jna@5.7.0/com.sun.jna.NativeLibrary.getInstance(Unknown Source)
	at com.sun.jna@5.7.0/com.sun.jna.Native.register(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.natives.Libirecovery.<clinit>(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.LibimobiledeviceUtil.waitForRecovery(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.UnsatisfiedLinkError: libirecovery.so: cannot open shared object file: No such file or directory
		at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.lang.UnsatisfiedLinkError: libirecovery.so: cannot open shared object file: No such file or directory
		at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
		... 12 more
	Suppressed: java.io.IOException: Native library (linux-x86-64/libirecovery.so) not found in resource path ()
		at com.sun.jna@5.7.0/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
		... 12 more

This below is me:
➜  ~ irecovery -v -n
Attempting to connect...
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
Command completed successfully
```

**Comment by Mythbusters123** [comment]
Im pretty sure you need to run `brew install libimobiledevice` or something like that

**Comment by mmhobi7** [comment]
> Im pretty sure you need to run `brew install libimobiledevice` or something like that

I'm on Ubuntu no Mac OS, but for reference yes it would be 
sudo apt install libimobiledevice irecovery

**Comment by airsquared** [comment]
The libirecovery library is actually used by blobsaver itself for reading the device information, not tsschecker.

I could add an error message if blobsaver is unable to find a native library to ensure the user has it installed and suggesting a solution to create a symlink if the name is different.

**Comment by mmhobi7** [comment]
I looked but couldn't find where blobsaver calls for irecovery.so. It could
fallback on irecovery-1.0.so (or whatever I called it in post 1)

**Comment by airsquared** [comment]
That's a good idea too and would probably be easier.

blobsaver looks for irecovery here: https://github.com/airsquared/blobsaver/blob/50c49c7d254cf0c667f842523db0982ba1b30ac2/src/main/java/airsquared/blobsaver/app/natives/Libirecovery.java#L86-L88

**Comment by airsquared** [comment]
Added in v3.0.2.

**Comment by olivertzeng** [comment]
> brew install libimobiledevice

linuxbrew
