### ISSUE TITLE
"Unable to exteact BuildManifest"

### ISSUE THREAD

**Issue by Leungsiuyin** [airsquared/blobsaver#294]
**Describe the bug**
Got some Error when saving blobs. In win10x64 OS.

**Desktop:**
 - OS Version:14.1
 - iOS Device: (if applicable):iphone 12 ProMax

**Checklist (place an x between the brackets to mark as completed):**
 - [ x ] I have made sure I am on the latest version of blobsaver
 - [ x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ x ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Utils$HttpChannel.ensureOpen(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Utils$HttpChannel.size(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.tryToLocateSignature(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
```

**Comment by airsquared** [comment]
I'm unable to reproduce this issue, do you get this error every time you try to save blobs?

**Comment by Leungsiuyin** [comment]
That is Java environment problem, saving blobs success by reinstall Java environment

**Comment by airsquared** [comment]
Good that it fixed it, but odd because blobsaver doesn't even require Java anymore. It might just have been fixed by some other side effect of reinstalling Java.
