### ISSUE TITLE
shsh2 blob saving fails with iOS 15 beta

### ISSUE THREAD

**Issue by timonline** [airsquared/blobsaver#303]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Trying to save shsh blobs for iPhone 12 Pro Max on iOS 15 beta using url [](https://download.developer.apple.com/WWDC_2021/iOS_15_beta/iPhone134_15.0_19A5261w_Restore.ipsw)

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Utils$HttpChannel.ensureOpen(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Utils$HttpChannel.size(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.tryToLocateSignature(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.1/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by Absolucy** [comment]
It only fails on 15.0 beta 1, due to the fact that IPSW requires a dev account to download, I believe. Beta 2 seems to work fine, though.

**Comment by timonline** [comment]
> It only fails on 15.0 beta 1, due to the fact that IPSW requires a dev account to download, I believe. Beta 2 seems to work fine, though.

You were absolutely right, it works now with the beta 2 link. Thank you, closing this bug

**Comment by Absolucy** [comment]
yeah, to save beta 1 blobs you need to get the ipsw somehow, then manually run `tsschecker` and use it's buildmanifest.plist
