### ISSUE TITLE
Doesn't copy APNonce to field after successful retrieval

### ISSUE THREAD

**Issue by the1gamerdude** [airsquared/blobsaver#314]
**Describe the bug**
Lost connectivity after reading from the device. Blobsaver retrieves APNonce but won't use it as it gets a error code (-7, or -8) after reboot (sometimes, other times it's just the no devices found error). It also does not recognize a connected phone if it reads from the devices a second time. 

i.e. 1. Read from device for ECID and Identifier.
2. Read from device for APNonce
3. Returns Error: No devices found.

Or if I unplug and replug it into my computer until Read from device for APNonce gets past initial connection verification and puts it into recovery mode:

1. Read device for APNonce (selected Jailbroken)
2. Puts device into recovery mode
3. Displays Retrieved APNonce, leaving recovery mode (not exact text)
4. Please unlock your device, then immediately goes to 5. 
5. Error: No Devices Found
6. Unable to click finish as it hasn't found the phone after leaving recovery mode, and so I click the X on the error box and no APNonce is saved

Essentially, it can get the APNonce, it just errors faster on springboard loading far faster than I can unlock the device and click finish.

**Screenshots**
When used from fresh reboot (not in jailbroken state)
![image](https://user-images.githubusercontent.com/4284442/127082991-3df64aa8-0b5d-48b4-a536-86e54b8b4eeb.png)

Read from when a jailbroken state

![image](https://user-images.githubusercontent.com/4284442/127083276-79bcf433-c1d9-49e5-8f57-0dc8ab34bd71.png)

**Desktop:**
 - OS Version: Windows 10 ( 20H2, OS Build 19042.1110)
 - iTunes Version: 12.11.3
 - iOS Device: iPhone 12 Max Pro (iPhone 13,4). Jailbroken on iOS 14.3 using Taurine. (previously jailbroken with Unc0ver before Taurine was available)

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
Stacktrace of error pasted. Rest is just repeated text box error messages

```
at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.throwIfNeeded(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.getMobileGestaltKey(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.getGenerator(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by hbrtv** [comment]
From Reddit post, the temp solution to this problem is to unplug from computer after exsiting  from Recovery mode.And plug back after enter password to unlock iphone.
