### ISSUE TITLE
cannot connect to phone ios 14.7

### ISSUE THREAD

**Issue by DeerSpotter** [airsquared/blobsaver#317]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [ ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.UnsatisfiedLinkError: Unable to load library 'imobiledevice':
The operating system cannot run %1.

The operating system cannot run %1.

The specified module could not be found.

Native library (win32-x86-64/imobiledevice.dll) not found in resource path ()
	at com.sun.jna@5.7.0/com.sun.jna.NativeLibrary.loadLibrary(Unknown Source)
	at com.sun.jna@5.7.0/com.sun.jna.NativeLibrary.getInstance(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.natives.NativeUtils.register(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.natives.Libimobiledevice.<clinit>(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.lockdowndClientFromConnectedDevice(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.getKeyFromConnectedDevice(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.getECID(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.Controller.readInfo(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.UnsatisfiedLinkError: The operating system cannot run %1.

		at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
		... 65 more
	Suppressed: java.lang.UnsatisfiedLinkError: The operating system cannot run %1.

		at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
		... 65 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
		... 65 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/imobiledevice.dll) not found in resource path ()
		at com.sun.jna@5.7.0/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
		... 65 more
	Suppressed: java.lang.UnsatisfiedLinkError: Unable to load library 'imobiledevice-1.0':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/imobiledevice-1.0.dll) not found in resource path ()
		... 65 more
		Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

			at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
			... 65 more
		Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

			at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
			... 65 more
		Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

			at com.sun.jna@5.7.0/com.sun.jna.Native.open(Native Method)
			... 65 more
		Suppressed: java.io.IOException: Native library (win32-x86-64/imobiledevice-1.0.dll) not found in resource path ()
			at com.sun.jna@5.7.0/com.sun.jna.Native.extractFromResourcePath(Unknown Source)
			... 65 more

```

**Comment by DeerSpotter** [comment]
Ran as administrator and problem went away.

**Comment by goopy13** [comment]
@DeerSpotter You should close this issue.
