### ISSUE TITLE
APNonce extraction on iPhone 12 Pro Max (14.5.1) non-jailbroken app hang during phone switchover to restore mode...

### ISSUE THREAD

**Issue by ab17182** [airsquared/blobsaver#319]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

App doesn't ever extract AP nonce from unjailbroken iPhone 12 Pro Max in unjailbroken and restore mode state. 

Screen is stuck in restore mode until I manually click to get out of the mode in the app.

**Desktop:**
 - OS Version: Windows 10 Pro 20H2 
 - iOS Device: iPhone 12 Pro Max running 14.5.1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by ab17182** [comment]
Log output:

Read in normal mode: bcd470130079cec8a4aa613603e666498ca67b35ab92ed295a4656bbff438643
airsquared.blobsaver.app.LibimobiledeviceUtil$LibimobiledeviceException: irecovery error: code=-3

If your device is still in recovery mode, use the "Exit Recovery Mode" option from the help menu.
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.throwIfNeeded(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil.waitForRecovery(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.0.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by airsquared** [comment]
Try different USB cables, different USB ports on your computer, and removing any intermediate devices between your USB cable and computer like USB hubs.
