### ISSUE TITLE
Could not extract buildmanifest

### ISSUE THREAD

**Issue by WayneBishop1** [airsquared/blobsaver#335]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.nio.channels.ReadableByteChannel.close()" because "this.ch" is null
		at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.Utils$HttpChannel.close(Unknown Source)
		... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://updates.cdn-apple.com/2021FallFCS/fullreshttps://updates.cdn-apple.com/2021FallFCS/fullrestores/071-96809/2CB6C4F9-A703-4721-9ADF-C3D3649D98CB/iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_15.0_19A344_Restore.ipsw
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.Utils$HttpChannel.ensureOpen(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.Utils$HttpChannel.size(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.tryToLocateSignature(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more

**Screenshots**

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: (if applicable) Iphone XS Max 11,6

**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x ] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```

**Comment by airsquared** [comment]
Did you manually specify a URL for the IPSW?
