### ISSUE TITLE
[Error] Unable to extract BuildManifest v3.0.2

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [airsquared/blobsaver#339]
**Describe the bug**
Fails to save ios 14.8 Blobs (Stock FW) iPhone 12 Pro
specifying lower versions such as 14.7.1 works fine.

**Screenshots**

![Screen Shot 2021-09-19 at 12 53 38 am](https://user-images.githubusercontent.com/2242880/133892961-ca9c7175-1fb9-4a2f-a463-b488807822d1.jpg)

**Desktop:**
 - OS Version: macOS 11.6
 - iOS Device: iPhone 12 Pro, 14.7

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more
```

**Comment by airsquared** [comment]
Please try opening the debug log, attempt to save blobs again, then paste the entire debug log output here.

**Comment by XxUnkn0wnxX** [comment]
With All Signed Versions Ticked:
```
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-03652/02507F5B-9411-410B-B837-C16AD6E54410/iPhone13,2,iPhone13,3_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98054/06E594D3-1C74-4192-A0DE-38C0B0AB28BD/iPhone13,2,iPhone13,3_14.8_18H17_Restore.ipsw, signed=true], IOSVersion[versionString=14.7.1, ipswURL=https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-73682/4FEC25C8-8745-471E-A8DE-EF7572030F44/iPhone13,2,iPhone13,3_14.7.1_18G82_Restore.ipsw, signed=true]]
tsschecker = /Applications/blobsaver.app/Contents/MacOS/tsschecker
Extracted to /var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest10676134146996308472.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPhone13,3, --ecid, 1C30C01412001E, --save-path, /Users/ovidijus/Blobs, --boardconfig, d53pap, --apnonce, 5e81efc52ee866abf079214e57f28da560a4af1b209430f79a9311ffb4290d98, --generator, 0xca4d801f3a9902eb, --build-manifest, /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest10676134146996308472.plist]
tsschecker version: 1.0-4d5a39487d7f49c8cd23874c05c59dd38d010432
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0xca4d801f3a9902eb"
[TSSC] manually specified ECID to use, parsed "1C30C01412001E" to dec:7934900876476446 hex:1c30c01412001e
[TSSC] manually specified apnonce to use, parsed "5e81efc52ee866abf079214e57f28da560a4af1b209430f79a9311ffb4290d98" to hex:5e81efc52ee866abf079214e57f28da560a4af1b209430f79a9311ffb4290d98
[TSSC] opening /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest10676134146996308472.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone13,3 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS version is not being signed for device iPhone13,3
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Specifying 14.8 as the version
```
iosVersions = [IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98054/06E594D3-1C74-4192-A0DE-38C0B0AB28BD/iPhone13,2,iPhone13,3_14.8_18H17_Restore.ipsw, signed=true]]
tsschecker = /Applications/blobsaver.app/Contents/MacOS/tsschecker
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.2/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more
```

Specifying 15.0 version
```
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-03652/02507F5B-9411-410B-B837-C16AD6E54410/iPhone13,2,iPhone13,3_15.0_19A346_Restore.ipsw, signed=true]]
tsschecker = /Applications/blobsaver.app/Contents/MacOS/tsschecker
Extracted to /var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest15219070395843738389.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPhone13,3, --ecid, 1C30C01412001E, --save-path, /Users/ovidijus/Blobs, --boardconfig, d53pap, --apnonce, 5e81efc52ee866abf079214e57f28da560a4af1b209430f79a9311ffb4290d98, --generator, 0xca4d801f3a9902eb, --build-manifest, /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest15219070395843738389.plist]
tsschecker version: 1.0-4d5a39487d7f49c8cd23874c05c59dd38d010432
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0xca4d801f3a9902eb"
[TSSC] manually specified ECID to use, parsed "1C30C01412001E" to dec:7934900876476446 hex:1c30c01412001e
[TSSC] manually specified apnonce to use, parsed "5e81efc52ee866abf079214e57f28da560a4af1b209430f79a9311ffb4290d98" to hex:5e81efc52ee866abf079214e57f28da560a4af1b209430f79a9311ffb4290d98
[TSSC] opening /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest15219070395843738389.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone13,3 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: iOS 15.0 is not being signed for device iPhone13,3
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by airsquared** [comment]
Please try that again with the latest v3.0.3.

**Comment by XxUnkn0wnxX** [comment]
15.0 goes through, 14.8 still same error. (this is concerning if ios versions are hit n miss like this)

Video: https://www.dropbox.com/s/vp5izakdumrl7jy/blobsaver%20error%20v3.0.3.mp4?dl=0

```
Read in normal mode: 9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3
iosVersions = [IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98054/06E594D3-1C74-4192-A0DE-38C0B0AB28BD/iPhone13,2,iPhone13,3_14.8_18H17_Restore.ipsw, signed=true]]
tsschecker = /Applications/blobsaver.app/Contents/MacOS/tsschecker
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.0.3/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.3/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.3/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-03652/02507F5B-9411-410B-B837-C16AD6E54410/iPhone13,2,iPhone13,3_15.0_19A346_Restore.ipsw, signed=true]]
Extracted to /var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest9901225936697285995.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPhone13,3, --ecid, 1C30C01412001E, --save-path, /Users/ovidijus/Blobs, --boardconfig, d53pap, --apnonce, 9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3, --generator, 0x14acf824e4e03bd2, --build-manifest, /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest9901225936697285995.plist]
tsschecker version: 0.-
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0x14acf824e4e03bd2"
[TSSC] manually specified ECID to use, parsed "1C30C01412001E" to dec:7934900876476446 hex:1c30c01412001e
[TSSC] manually specified apnonce to use, parsed "9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3" to hex:9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3
[TSSC] opening /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest9901225936697285995.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Checking BuildIdentity 2
[TSSR] Checking BuildIdentity 3
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to not request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!

iOS 15.0 for device iPhone13,3 IS being signed!
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-03652/02507F5B-9411-410B-B837-C16AD6E54410/iPhone13,2,iPhone13,3_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98054/06E594D3-1C74-4192-A0DE-38C0B0AB28BD/iPhone13,2,iPhone13,3_14.8_18H17_Restore.ipsw, signed=true]]
Extracted to /var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest3431788664977742024.plist
Running: [/Applications/blobsaver.app/Contents/MacOS/tsschecker, --nocache, --save, --device, iPhone13,3, --ecid, 1C30C01412001E, --save-path, /Users/ovidijus/Blobs, --boardconfig, d53pap, --apnonce, 9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3, --generator, 0x14acf824e4e03bd2, --build-manifest, /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest3431788664977742024.plist]
tsschecker version: 0.-
Libfragmentzip version: 7951fa1e40415a630cd2d4401b2ebb261b0a46a2 - 53
[TSSC] manually specified generator "0x14acf824e4e03bd2"
[TSSC] manually specified ECID to use, parsed "1C30C01412001E" to dec:7934900876476446 hex:1c30c01412001e
[TSSC] manually specified apnonce to use, parsed "9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3" to hex:9ab9f782a492f4ecfd3bfc0ceb8ebcbc9c1dc95494963ec504d2b70bfce072e3
[TSSC] opening /private/var/folders/m6/vln7p7nx73l3r5q5bg7h1n9h0000gn/T/BuildManifest3431788664977742024.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Checking BuildIdentity 2
[TSSR] Checking BuildIdentity 3
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] Checking BuildIdentity 0
[TSSR] Checking BuildIdentity 1
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to not request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!

iOS 15.0 for device iPhone13,3 IS being signed!
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.0.3/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.3/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.0.3/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 7 more
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.0.3/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 10 more
```

**Comment by GENHEN** [comment]
It might be because your temporary directory or blob directory is on a different drive than blobsaver, try moving the blob drive and your TEMP/TMP directory onto the same drive as blobsaver and the issue might go away
