### ISSUE TITLE
Change TSSChecker to allow iOS 15 to be saved

### ISSUE THREAD

**Issue by 306bobby** [airsquared/blobsaver#342]
**Describe the bug**
As stated, iOS 15 does not save
**Screenshots**
Not sure what ss would be helpful

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: 12 Mini on 14.6

**Checklist (place an x between the brackets to mark as completed):**
 - [x ] I have made sure I am on the latest version of blobsaver
 - [x ] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [ x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
iosVersions = [IOSVersion[versionString=null, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-02999/959BE5AC-0C86-486A-9E79-E0AB5BE258E0/iPhone13,1_15.0_19A346_Restore.ipsw, signed=null]]
Extracted to C:\Users\bobby\AppData\Local\Temp\BuildManifest18148528265896347546.plist
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone13,1, --ecid, 1528D00C10001E, --save-path, C:\Users\bobby\OneDrive\Documents\Jailbreak Blobs\iPhone 12, --boardconfig, d52gap, --apnonce, 30f4cc72a3cfc809afdd2fee150bc29cb8ddcf04fc523521bc0ca33046b433d0, --generator, 0xa54b85acbfe9b674, --build-manifest, C:\Users\bobby\AppData\Local\Temp\BuildManifest18148528265896347546.plist]
tsschecker version: 322.0-d7f6161052c973350fd7134a0b104fa2cb01d65f
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8
[TSSC] manually specified generator "0xa54b85acbfe9b674"
[TSSC] manually specified ECID to use, parsed "1528D00C10001E" to dec:5955848531607582 hex:1528d00c10001e
[TSSC] manually specified apnonce to use, parsed "30f4cc72a3cfc809afdd2fee150bc29cb8ddcf04fc523521bc0ca33046b433d0" to hex:30f4cc72a3cfc809afdd2fee150bc29cb8ddcf04fc523521bc0ca33046b433d0
[TSSC] opening C:\Users\bobby\AppData\Local\Temp\BuildManifest18148528265896347546.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone13,1 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS version is not being signed for device iPhone13,1
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
iosVersions = [IOSVersion[versionString=15.0, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/002-02999/959BE5AC-0C86-486A-9E79-E0AB5BE258E0/iPhone13,1_15.0_19A346_Restore.ipsw, signed=true], IOSVersion[versionString=14.8, ipswURL=https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98042/78053B50-F6B0-4B18-9339-611F7B7D97A5/iPhone13,1_14.8_18H17_Restore.ipsw, signed=true], IOSVersion[versionString=14.7.1, ipswURL=https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-74134/2D820B7F-79B3-48FC-92F3-11332E96DF0B/iPhone13,1_14.7.1_18G82_Restore.ipsw, signed=true]]
Extracted to C:\Users\bobby\AppData\Local\Temp\BuildManifest2175652695672692941.plist
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone13,1, --ecid, 1528D00C10001E, --save-path, C:\Users\bobby\OneDrive\Documents\Jailbreak Blobs\iPhone 12, --boardconfig, d52gap, --apnonce, 30f4cc72a3cfc809afdd2fee150bc29cb8ddcf04fc523521bc0ca33046b433d0, --generator, 0xa54b85acbfe9b674, --build-manifest, C:\Users\bobby\AppData\Local\Temp\BuildManifest2175652695672692941.plist]
tsschecker version: 322.0-d7f6161052c973350fd7134a0b104fa2cb01d65f
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8
[TSSC] manually specified generator "0xa54b85acbfe9b674"
[TSSC] manually specified ECID to use, parsed "1528D00C10001E" to dec:5955848531607582 hex:1528d00c10001e
[TSSC] manually specified apnonce to use, parsed "30f4cc72a3cfc809afdd2fee150bc29cb8ddcf04fc523521bc0ca33046b433d0" to hex:30f4cc72a3cfc809afdd2fee150bc29cb8ddcf04fc523521bc0ca33046b433d0
[TSSC] opening C:\Users\bobby\AppData\Local\Temp\BuildManifest2175652695672692941.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

iOS 15.0 for device iPhone13,1 IS NOT being signed!
airsquared.blobsaver.app.TSS$TSSException: The iOS version is not being signed for device iPhone13,1
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.parseTSSLog(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.0.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by Tanbeer191** [comment]
For a better explanation, you need this basically.

https://github.com/1Conan/tsschecker/commit/1b5e82e3c8275874a3595c2c57cd5ea9921dc2e2

**Comment by airsquared** [comment]
Fixed in v3.0.3.

**Comment by iambenmitchell** [comment]
Seeing this issue again. 3.1.0
<img width="967" alt="Screenshot 2022-04-08 at 01 51 45" src="https://user-images.githubusercontent.com/27426792/162342158-328d359e-4e94-44b7-a0f0-a787fa0b7c62.png">

**Comment by airsquared** [comment]
This might just be because iOS 15.4 was just unsigned and the APIs haven't updated to reflect that yet. The issue should have automatically resolved itself in a few hours (maybe taking up to a day).
