### ISSUE TITLE
"lockdownd error code=-20" when clicking read from device

### ISSUE THREAD

**Issue by Michael2987** [airsquared/blobsaver#454]
When I plugged in my iPhone XR into my pc via the front port, no USB hub (even tried the rear port too) 
took a few seconds for windows to actually install my device then it asked to trust I clicked "trust" entered the password on my pc, on blob saver where it says ECID I hit "read from device" took like 1/2 a second to spit that error at me. (error shown below)

![blobsaver_8a3N01Sdjm](https://user-images.githubusercontent.com/76879913/174654391-ca974e0c-4975-4d07-a0ea-37e0261dfe51.png)
![blobsaver_QVn3RTvYwZ](https://user-images.githubusercontent.com/76879913/174654392-3d659c9d-727e-4628-a89d-3b40f5bd9022.png)

 - Windows Server 2012 R2 (build 9600)
 - iOS Device: iPhone XR Global iOS16b1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blob saver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blob saver
 *Regarding the troubleshooting tactics, I also updated iTunes from 11.4 - 12.8 (11.4 and 12.8 were and still are both giving me that same error. I was on 11.4 at first currently experiencing that code=20 error)

**Log:**

lockdownd error: code=-20
airsquared.blobsaver.app.LibimobiledeviceUtil$LibimobiledeviceException: lockdownd error: code=-20
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil.throwIfNeeded(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil.lockdowndClientFromConnectedDevice(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil.enterRecovery(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by airsquared** [comment]
Please try the solutions listed [here](https://github.com/airsquared/blobsaver/wiki/Errors-reading-from-device).
