### ISSUE TITLE
Cant save to TSS Server

### ISSUE THREAD

**Issue by BlueScriptsAndDies** [airsquared/blobsaver#462]
So when ever I try to save to TSS  Saver it wont let me, but  I  can save to SHSH host.

I'm on iOS 15.5 beta 4, iPad 6th gen

And for the OS windows 10

Image:
![2022-07-26 (3)](https://user-images.githubusercontent.com/105551126/181057945-38812ba5-0c4d-47ce-be08-93185c39ef5a.png)

Log:
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "<local5>" is null
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.TSS.saveBlobsTSSSaver(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by airsquared** [comment]
Do you still get this error every time?
