### ISSUE TITLE
Unable to read APNonce from device

### ISSUE THREAD

**Issue by k4zo** [airsquared/blobsaver#472]
**Describe the bug**
Attempting to "read from device" and boot into recovery mode causes an error in the program and subsequent phone getting stuck in recovery mode

**Screenshots**
N/A

**Desktop:**
 - OS Version: Windows 7 (6.1.7601)
 - iOS Device: iPhone 13 (iPhone14,5)

**Checklist (place an x between the brackets to mark as completed):**
 - [X] I have made sure I am on the latest version of blobsaver
 - [X/?] I have checked other open issues to see if my problem has already been reported (unsure if it already has been, because the one remotely similar open issue is very unhelpful, specifies nothing, is flaired as "question" rather than "bug", and provides no logs)
 - [X] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.NullPointerException: Cannot invoke "com.sun.jna.Pointer.getByteArray(long, int)" because "<local1>.ap_nonce" is null
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil.getApnonce(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by airsquared** [comment]
Do you still get this issue with the latest version?
