### ISSUE TITLE
Trying to save (working) and send blobs to TTS Saver and SHSH Host

### ISSUE THREAD

**Issue by freezed-purple** [airsquared/blobsaver#497]
-------------------------------------------------------------

**Describe the bug**
Trying to save (working) and send blobs to TTS Saver and SHSH Host

**Screenshots**

**Desktop:**
 - OS Version: Windows 11 22H2
 - iOS Device: iOS 15.5B4

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "<local5>" is null
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.TSS.saveBlobsTSSSaver(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.2.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by airsquared** [comment]
I will close this issue due to inactivity, but if you are still having issues you can reopen it.
