### ISSUE TITLE
fails to save and prompts to open github issue

### ISSUE THREAD

**Issue by mailinglists35** [airsquared/blobsaver#528]
**Describe the bug**
fails to save

**Screenshots**

**Desktop:**
 - OS Version: 15.0
 - iOS Device: 13 mini

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
airsquared.blobsaver.app.TSS$TSSException: Unable to extract BuildManifest.
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveFor(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error on ZipFile ipsw
	at blobsaver.merged.module@3.4.1/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at blobsaver.merged.module@3.4.1/org.apache.commons.compress.archivers.zip.ZipFile.<init>(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Utils.extractManifestFromZip(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Utils.extractBuildManifest(Unknown Source)
	... 8 more
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.nio.channels.ReadableByteChannel.close()" because "this.ch" is null
		at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Network$HttpChannel.close(Unknown Source)
		... 10 more
Caused by: java.net.UnknownHostException: updates.cdn-apple.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Network$HttpChannel.ensureOpen(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Network$HttpChannel.size(Unknown Source)
	at blobsaver.merged.module@3.4.1/org.apache.commons.compress.archivers.zip.ZipFile.tryToLocateSignature(Unknown Source)
	at blobsaver.merged.module@3.4.1/org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(Unknown Source)
	at blobsaver.merged.module@3.4.1/org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(Unknown Source)
	at blobsaver.merged.module@3.4.1/org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(Unknown Source)
	... 12 more

```

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/209989730-59f16f92-f6c4-4157-a80d-f0cd32b45421.png)

**Comment by mailinglists35** [comment]
ah lol wait a minute, I think I know what caused this: I'm blocking apple OTAs in my dns.
maybe this should fail more gracefully with a clearer message when the app cannot resolve apple activation fqdn server names.
