### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by NotEclypse** [airsquared/blobsaver#530]
**Describe the bug**
I tried saving my blobs for iPhone 14 Pro and this is what I got, I tried all signed versions and including betas, but unticking including betas didn't help at all.

**Screenshots**
<img width="688" alt="Screenshot 2023-01-01 at 13 19 48" src="https://user-images.githubusercontent.com/97740933/210170362-9cf29342-5a24-47f9-8cf3-ada3a360c074.png">

**Desktop:**
 - OS Version: MacOS Ventura 13.0.1
 - iOS Device: iPhone 14 Pro (iPhone15,2)

**Checklist:**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsSHSHHost(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.stream.JsonReader.beginObject(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	... 12 more
```

**Comment by mawech** [comment]
Since this is the first bug opened I'm going to comment here.
I turned on debug log and it looks like some network issue with the SHSH host. If I turn off "Also save to SHSH host" everything works fine.

Debug log in the second post, since I don't know how to format it properly.

**Comment by mawech** [comment]
iosVersions = [IOSVersion[versionString=12.5.6, buildid=16H71, ipswURL=https://updates.cdn-apple.com/2021WinterFCS/fullrestores/012-51870/2A494DC9-8DE4-43F8-B084-87E91D5AF9BA/iPhone_4.7_12.5.6_16H71_Restore.ipsw, signed=true]]
tsschecker = C:\Data\Jailbreak\blobsaver\blobsaver-3.4.1_installed\lib\tsschecker.exe
Directly downloaded to C:\Users\franz\AppData\Local\Temp\BuildManifest8898958379736744421.plist
Running: [C:\Data\Jailbreak\blobsaver\blobsaver-3.4.1_installed\lib\tsschecker.exe, --nocache, --save, --device, iPhone7,2, --ecid, 1E5D8210EBE826, --boardconfig, n61ap, --generator, 0x1111111111111111, --save-path, C:\Data\Jailbreak\Blobs, --build-manifest, C:\Users\franz\AppData\Local\Temp\BuildManifest8898958379736744421.plist]
tsschecker version: 0.419-ec6e6fdfe06c8b7a5f48983eb78738fa9b6a876d
libfragmentzip version: 0.Debug-Build: Dec 14 2022 19:22:07-RELEASE
[TSSC] manually specified generator "0x1111111111111111"
[TSSC] manually specified ECID to use, parsed "1E5D8210EBE826" to dec:8547062512347174 hex:1e5d8210ebe826
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
also requesting APTicket for installType=Update
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 2... Request URL set to https://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 3... Request URL set to http://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 4... Request URL set to http://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 5... Request URL set to http://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 6... Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 7... Request URL set to https://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 8... Request URL set to https://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 9... Request URL set to http://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 10... Request URL set to http://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 11... Request URL set to http://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 12... Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 13... Request URL set to https://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 14... Request URL set to https://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 15... Saved shsh blobs!

iOS 12.5.6 for device iPhone7,2 IS being signed!
{selected_firmware=All, ecid=1E5D8210EBE826, device=iPhone7,2, boardconfig=n61ap}
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at com.google.gson@2.10/com.google.gson.Gson.fromJson(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsSHSHHost(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson@2.10/com.google.gson.stream.JsonReader.beginObject(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	at com.google.gson@2.10/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source)
	... 12 more

**Comment by mawech** [comment]
Also https://verify.shsh.host currently returns a "502 Bad Gateway" error. Maybe that's the issue.

**Comment by airsquared** [comment]
The problem is entirely with SHSH Host and is not something that blobsaver can fix. If you disable "Also save to SHSH Host" it should work fine.

In the next update, I'll add an error message that better explains this.

**Comment by airsquared** [comment]
This has been fixed in v3.5.0.
