### ISSUE TITLE
Error saving to TSS and SHSH

### ISSUE THREAD

**Issue by tommygeexx** [airsquared/blobsaver#541]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
Hello! just got the iphone 14 Pro Max and updated Blobsaver. I am now getting and error when i try to automatically save blobs to TSS saver and SHSH

**Screenshots**
![Blob Error](https://user-images.githubusercontent.com/108078738/213936063-449f2997-cb6e-4ab8-8c4b-776974acdd4d.png)

**Desktop:**
 - OS Version: Windows 11
 - iOS Device: (if applicable) iPhone 14 Pro Max iOS 16.2

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver

 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
iosVersions = [IOSVersion[versionString=16.2, buildid=20C65, ipswURL=https://updates.cdn-apple.com/2022FallFCS/fullrestores/032-13992/B2DDFE90-E40A-43AF-BFD1-0458E13D8C0F/iPhone15,3_16.2_20C65_Restore.ipsw, signed=true]]
Already Saved: 6795901283844126_iPhone15,3_d74ap_16.2-20C65_30b0578e367f620bb930638a28fbb937ed742a59c7a7ab448c623ba8f2cd84e2.shsh2
{deviceIdentifier=iPhone15,3, boardConfig=d74ap, ecid=6795901283844126, generator=0x62021276685b54e3, apnonce=30b0578e367f620bb930638a28fbb937ed742a59c7a7ab448c623ba8f2cd84e2}
java.io.IOException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Network.makePOSTRequest(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsTSSSaver(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InternalError: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.WEPollSelectorImpl.wakeup(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.register(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.registerEvent(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Unknown Source)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source)
	... 11 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.IOUtil.write1(Native Method)
	... 32 more
{selected_firmware=All, ecid=1824D611F3C01E, generator=0x62021276685b54e3, device=iPhone15,3, apnonce=30b0578e367f620bb930638a28fbb937ed742a59c7a7ab448c623ba8f2cd84e2, boardconfig=d74ap}
java.io.IOException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.Network.makePOSTRequest(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.saveBlobsSHSHHost(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.4.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InternalError: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.WEPollSelectorImpl.wakeup(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.register(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.registerEvent(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Unknown Source)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source)
	... 11 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.IOUtil.write1(Native Method)
	... 32 more

```

![Blob Error](https://user-images.githubusercontent.com/108078738/213936256-1b5270d0-e4ad-4962-b27e-60173f027538.png)

**Comment by airsquared** [comment]
I'm having no issues on my end. It is possible both TSS Saver and SHSH Host were down when you tried to save blobs but are working now.

If not, it's likely an error with your own computer. An antivirus could be interfering with blobsaver, your internet connection might be unstable, you might have an issue with your DNS configuration, or something else.

**Comment by blanxd** [comment]
TSS Saver it looks like it might be sometimes having a few issues but mostly ok. But about SHSH Host, I just found the IPv6 version isn't working (it's serving the contents of api.arx8x.net instead, together with its SSL cert), for a few weeks now I think. I only made a note to arx8x about it in a [twitter thread reply](https://twitter.com/insan1d/status/1615329796841680898) but hopefully he can pick it up. @tommygeexx if you turn off your IPv6 then it should work fine.

**Comment by arx8x** [comment]
I've run some major release upgrades on the server recently. Maybe the config files need some changes that I overlooked. That could be a reason for this behavior. I'll look into this and update the thread.

**Comment by tommygeexx** [comment]
Ahh thank you guys ! TSS seems to be back up , but I’m glad it was them and not something with the app or my computer 

thank you!!

**Comment by airsquared** [comment]
Moving this issue to a discussion.
