### ISSUE TITLE
"Check your internet connection" because of certificates error

### ISSUE THREAD

**Issue by KirkLandTrip** [airsquared/blobsaver#549]
**Describe the bug**
After clicking "Go" to save the blobs I'm getting the "Check your internet connection" error window.  
Checking in the debug log it seems that the problem is 
"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"
This computer is **behind a university Firewall** which I, obviously, can not configure.
I can't use this iPhone with another computer without a firewall.
I suspect that the firewall does SSL/TLS interception by providing self-signed certificates.
My browser doesn't have any problem accessing websites via TLS, so a matching "root certificate" is probably installed on this machine.
I don't really know how this works on Windows or how to fix it in java, I'm just guessing based on my networking knowledge.

**Screenshots**
![image](https://user-images.githubusercontent.com/112394801/214543317-02c1bb02-7e57-4614-a4b2-dc711c2e4ee5.png)

**Desktop:**
 - OS Version: Windows 10 x64 20H2
 - iOS Device: 16.0.3

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
airsquared.blobsaver.app.TSS$TSSException: Saving blobs failed. Check your internet connection.
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Network.makeRequest(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getFirmwareList(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getSignedFirmwares(Unknown Source)
	... 8 more
	Suppressed: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
		at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
		at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
		at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
		at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
		at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
		at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
		at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
		at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
		at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
		at java.base/java.net.URL.openStream(Unknown Source)
		at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Network.makeRequest(Unknown Source)
		at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
		... 10 more
	Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
		at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
		at java.base/sun.security.validator.Validator.validate(Unknown Source)
		at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
		at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
		... 30 more
	Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
		at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
		at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
		... 35 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 34 more
airsquared.blobsaver.app.TSS$TSSException: Saving blobs failed. Check your internet connection.
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Network.makeRequest(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getFirmwareList(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getSignedFirmwares(Unknown Source)
	... 8 more
	Suppressed: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
		at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
		at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
		at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
		at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
		at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
		at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
		at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
		at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
		at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
		at java.base/java.net.URL.openStream(Unknown Source)
		at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Network.makeRequest(Unknown Source)
		at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
		... 10 more
	Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
		at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
		at java.base/sun.security.validator.Validator.validate(Unknown Source)
		at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
		at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
		... 30 more
	Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
		at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
		at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
		... 35 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 34 more
```

**Comment by airsquared** [comment]
Open the file `C:\Program Files\blobsaver\app\blobsaver.cfg` and add the following lines to the end:
```
java-options=-Djavax.net.ssl.trustStore=NUL
java-options=-Djavax.net.ssl.trustStoreType=Windows-ROOT
```
You will do need to do this on every installation of blobsaver.

**Comment by KirkLandTrip** [comment]
Thank you for responding.

I tried both `Windows-ROOT` and `Windows-MY` and it didn't work, but the error changed.
Now I'm getting this error message box:
"An unknown error occurred"
![image](https://user-images.githubusercontent.com/112394801/215472248-75fef499-f751-4df1-9e57-3e8ba3e1c159.png)

The clipboard content (and the content of the debug log) is:
```
java.lang.NoClassDefFoundError: Could not initialize class airsquared.blobsaver.app.Network
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getFirmwareList(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.getSignedFirmwares(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError: Exception java.io.UncheckedIOException: java.io.IOException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext) [in thread "Thread-3"]
	at java.net.http/jdk.internal.net.http.HttpClientImpl.<init>(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.create(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientBuilderImpl.build(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Network.<clinit>(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils$LatestVersion.request(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils._checkForUpdates(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Utils.lambda$checkForUpdates$1(Unknown Source)
	... 3 more
```

**Comment by nmka55** [comment]
I think this error is on tsssaver's side. If you go to their website, your browser will tell you it has no valid SSL certificates, thus it might be dangerous to visit the webpage. 

And if you go to shsh.host, their website is completely down.

Right now, only saving to local machine works properly I guess.
