### ISSUE TITLE
blobsaver says this

### ISSUE THREAD

**Issue by junebuggzy** [airsquared/blobsaver#555]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
A clear and concise description of what the bug is and the expected behavior.

**Screenshots**

**Desktop:**
 - OS Version:
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
If applicable, paste any log(s) here, on the lines between the backticks.
```java.lang.NoClassDefFoundError: Could not initialize class airsquared.blobsaver.app.natives.Libimobiledevice
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil.lockdowndClientFromConnectedDevice(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil.enterRecovery(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics@19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'imobiledevice':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/imobiledevice.dll) not found in resource path () [in thread "JavaFX Application Thread"]
	at com.sun.jna@5.13.0/com.sun.jna.NativeLibrary.loadLibrary(Unknown Source)
	at com.sun.jna@5.13.0/com.sun.jna.NativeLibrary.getInstance(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.natives.NativeUtils.register(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.natives.Libimobiledevice.<clinit>(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil.lockdowndClientFromConnectedDevice(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil.getLockdownValuePlist(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.LibimobiledeviceUtil.getECID(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Controller.readInfo(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@19/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@19/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@19/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	... 1 more

**Comment by airsquared** [comment]
Assuming problem is resolved as issue is closed.
