### ISSUE TITLE
Autosaving error

### ISSUE THREAD

**Issue by Anthirian** [airsquared/blobsaver#563]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**
When everything is filled out correctly, I can save manually, but I cannot enable autosave without producing errors.

**Screenshots**

N/A

**Desktop:**
 - OS Version: Windows 11
 - iOS Device: iPhone 12

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**

```
ERROR: The parameter is incorrect.

(15,23):UserId:Geert
java.net.UnknownHostException: www.google-analytics.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Analytics.sendRequest(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Analytics.collect(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Analytics.startBackground(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Background.startBackground(Unknown Source)
	at airsquared.blobsaver@3.5.0/airsquared.blobsaver.app.Controller.startBackgroundHandler(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@19/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@19/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@19/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@19/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Anthirian** [comment]
This is still an issue
