### ISSUE TITLE
Cannot invoke "com.google.gson.JsonArray.spliterator()"

### ISSUE THREAD

**Issue by Coll147** [airsquared/blobsaver#590]
**Describe the bug**
I get `Cannot invoke com.google.gson.JsonArray.spliterator()` error.

**Screenshots**
-----

**Desktop:**
 - OS Version: Windows 11
 - iOS Device: iPadAIR (A7) iOS12

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonArray.spliterator()" because "<local3>" is null
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaHubList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getBetaList(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.getSignedBetas(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by airsquared** [comment]
This is due to saving with betas enabled, but no betas are found. You will need to disable including betas for this device, I'll add a better error message to explain this in the next version.

**Comment by Coll147** [comment]
👍
