### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by nik312123** [airsquared/blobsaver#595]
**Describe the bug**
When I open blobsaver, I get the error message in the screenshots section. Neither a reinstall of the app or reboot resolves the issue.

**Screenshots**
<img width="360" alt="2023-07-11_22-27-29" src="https://github.com/airsquared/blobsaver/assets/24688726/daeb6062-aa5d-4d08-9147-25ad4ddfbeb6">

**Desktop:**
 - OS Version: macOS 12.6.7
 - iOS Device: (if applicable)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.net.SocketException: Bad file descriptor
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils$LatestVersion.request(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils._checkForUpdates(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.Utils.lambda$checkForUpdates$1(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by airsquared** [comment]
It will only save in the saved devices list, it doesn't save globally. This would be a new feature if you want the location to persist without any saved devices.

**Comment by nik312123** [comment]
Oh, perfect. I just needed to click on Save Device and overwrite the previous settings. I was just entering the information in and wondering why it wasn't saving. 😅
