### ISSUE TITLE
Error when trying to read APNonce from my 13 Pro Max

### ISSUE THREAD

**Issue by korboybeats** [airsquared/blobsaver#602]
-------------------------------------------------------------

**Describe the bug:**

When I try to retrieve my APNonce from my 13 Pro Max, it keeps giving me the error "LOCKDOWN_E_MUX_ERROR (-8)" after exiting out of recovery mode at the last step.

**Screenshots:**

![image](https://github.com/airsquared/blobsaver/assets/80824905/740ac852-6101-44ef-97a3-9cdf0845934a)

**Desktop:**
 - OS Version: Windows 11 (22H2 OS Build 22621.2070)
 - iOS Device: iPhone 13 Pro Max

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
airsquared.blobsaver.app.LibimobiledeviceUtil$LibimobiledeviceException: lockdownd error: LOCKDOWN_E_MUX_ERROR (-8)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.LibimobiledeviceUtil.throwIfNeeded(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at airsquared.blobsaver@3.5.1/airsquared.blobsaver.app.LibimobiledeviceUtil$GetApnonceTask.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
**Extra Information:**

I am using the normal Apple USB-C to Lightning cable plugged in the back of my PC in my motherboard.

**Comment by Gamr13** [comment]
My advice is avoid using the USB-C to Lightning cable for everything like this and jailbreaking. It's historically caused plenty of issues.

**Comment by airsquared** [comment]
Assuming that changing the cable works, I'll close the issue. If you still need help you can comment to reopen it.
