### ISSUE TITLE
Can't save blobs, error message "An unknown error occurred"

### ISSUE THREAD

**Issue by jayaoyama** [airsquared/blobsaver#631]
Your issue will be closed and/or deleted if you do not fill out this template.

Please remove the following line and the text above it before submitting this issue:

-------------------------------------------------------------

**Describe the bug**

Can't save blobs, error message "An unknown error occurred"

**Screenshots**

N/A

**Desktop:**
 - OS Version: macOS 13.0.1
 - iOS Device: iPhone X (does not occur with 3rd gen iPad Air)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because the return value of "java.lang.Exception.getMessage()" is null
	at airsquared.blobsaver@3.5.2/airsquared.blobsaver.app.TSS.getIOSVersions(Unknown Source)
	at airsquared.blobsaver@3.5.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver@3.5.2/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@20/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by airsquared** [comment]
The latest nightly build should either fix the issue or provide more information about what may have gone wrong.

**Comment by airsquared** [comment]
Closing this issue due to inactivity, but if you are still having issues you can reopen it.
