### ISSUE TITLE
Error encountered while trying to save blobs to TSS Saver and SHSH Host

### ISSUE THREAD

**Issue by mattsblack** [airsquared/blobsaver#660]
**Describe the bug**
When I saved blobs I checked the boxes to save blobs to TSS Saver and SHSH Host. It saved the blobs to my computer but I got an error when it tried saving blobs to TSS Saver. The error was 
>PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Screenshots**
![Blobsaver screenshot](https://github.com/airsquared/blobsaver/assets/47698245/9c6a18ba-bf73-40eb-95c4-d381223f165d)

**Desktop:**
 - OS Version: Windows 11 Pro
 - iOS Device: iPhone 13 iOS 17.4.1

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked other open issues to see if my problem has already been reported
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
```
iosVersions = [IOSVersion[versionString=17.4.1, buildid=21E237, ipswURL=https://updates.cdn-apple.com/2024WinterFCS/fullrestores/052-80312/8228E7C5-1197-4EEE-A8CC-D4E6CA4FC97C/iPhone14,5_17.4.1_21E237_Restore.ipsw, signed=true], IOSVersion[versionString=17.4.1, buildid=21E236, ipswURL=https://updates.cdn-apple.com/2024WinterFCS/fullrestores/052-72535/7FB1C2EC-870F-414E-BF50-6BC10AF4587B/iPhone14,5_17.4.1_21E236_Restore.ipsw, signed=true], IOSVersion[versionString=17.3.1, buildid=21D61, ipswURL=https://updates.cdn-apple.com/2024WinterFCS/fullrestores/052-41195/CD81E110-A937-4300-B06D-D762E23D2D84/iPhone14,5_17.3.1_21D61_Restore.ipsw, signed=true], IOSVersion[versionString=iOS 17.4 Release Candidate, buildid=21E217, ipswURL=https://updates.cdn-apple.com/2024WinterFCS/fullrestores/032-50632/6E6BF19C-2EF3-41C5-896E-A9AFDB3B1B4F/iPhone14,5_17.4_21E217_Restore.ipsw, signed=true]]
tsschecker = C:\Program Files\blobsaver\lib\tsschecker.exe
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone14,5, --ecid, [redacted], --boardconfig, d17ap, --apnonce, [redacted], --generator, [redacted], --save-path, [redacted], --build-manifest, C:\Users\Matthew\AppData\Local\Temp\BuildManifest331329189507638395.plist]
tsschecker version: 0.431.0-75f5c11420946c9d2b6ce3bacb35f0b7beddc84a-RELEASE
libfragmentzip version: 0.VERSION_COMMIT_COUNT_not_set-VERSION_COMMIT_SHA_not_set Build: Oct  1 2023 13:40:45-RELEASE
[TSSC] manually specified generator "[redacted]"
[TSSC] manually specified ECID to use, parsed "[redacted]" to dec:[redacted] hex:[redacted]
[TSSC] manually specified apnonce to use, parsed "[redacted]" to hex:[redacted]
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket for installType=Update
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket without a nonce
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Saved shsh blobs!

iOS 17.4.1 for device iPhone14,5 IS being signed!
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone14,5, --ecid, [redacted], --boardconfig, d17ap, --apnonce, [redacted], --generator, [redacted], --save-path, [redacted], --build-manifest, C:\Users\Matthew\AppData\Local\Temp\BuildManifest3586326881682459474.plist]
tsschecker version: 0.431.0-75f5c11420946c9d2b6ce3bacb35f0b7beddc84a-RELEASE
libfragmentzip version: 0.VERSION_COMMIT_COUNT_not_set-VERSION_COMMIT_SHA_not_set Build: Oct  1 2023 13:40:45-RELEASE
[TSSC] manually specified generator "[redacted]"
[TSSC] manually specified ECID to use, parsed "[redacted]" to dec:[redacted] hex:[redacted]
[TSSC] manually specified apnonce to use, parsed "[redacted]" to hex:[redacted]
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket for installType=Update
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket without a nonce
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Saved shsh blobs!

iOS 17.4.1 for device iPhone14,5 IS being signed!
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone14,5, --ecid, [redacted], --boardconfig, d17ap, --apnonce, [redacted], --generator, [redacted], --save-path, [redacted], --build-manifest, [redacted]]
tsschecker version: 0.431.0-75f5c11420946c9d2b6ce3bacb35f0b7beddc84a-RELEASE
libfragmentzip version: 0.VERSION_COMMIT_COUNT_not_set-VERSION_COMMIT_SHA_not_set Build: Oct  1 2023 13:40:45-RELEASE
[TSSC] manually specified generator "[redacted]"
[TSSC] manually specified ECID to use, parsed "[redacted]" to dec:[redacted] hex:[redacted]
[TSSC] manually specified apnonce to use, parsed "[redacted]" to hex:[redacted]
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket for installType=Update
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket without a nonce
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Saved shsh blobs!

iOS 17.3.1 for device iPhone14,5 IS being signed!
Running: [C:\Program Files\blobsaver\lib\tsschecker.exe, --nocache, --save, --device, iPhone14,5, --ecid, [redacted], --boardconfig, d17ap, --apnonce, [redacted], --generator, [redacted], --save-path, [redacted], --build-manifest, [redacted]]
tsschecker version: 0.431.0-75f5c11420946c9d2b6ce3bacb35f0b7beddc84a-RELEASE
libfragmentzip version: 0.VERSION_COMMIT_COUNT_not_set-VERSION_COMMIT_SHA_not_set Build: Oct  1 2023 13:40:45-RELEASE
[TSSC] manually specified generator "[redacted]"
[TSSC] manually specified ECID to use, parsed "[redacted]" to dec:[redacted] hex:[redacted]
[TSSC] manually specified apnonce to use, parsed "[redacted]" to hex:[redacted]
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket for installType=Update
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] Also requesting APTicket without a nonce
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Saved shsh blobs!

iOS 17.4 for device iPhone14,5 IS being signed!
{deviceIdentifier=iPhone14,5, boardConfig=d17ap, ecid=[redacted], generator=[redacted], apnonce=[redacted]}
javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.Network.makePOSTRequest(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.TSS.saveBlobsTSSSaver(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.TSS.call(Unknown Source)
	at javafx.graphics@21.0.1/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.validator.PKIXValidator.doValidate(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 22 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.base/java.security.cert.CertPathValidator.validate(Unknown Source)
	... 27 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Mar 28 16:26:59 EDT 2024
	at java.base/sun.security.x509.CertificateValidity.valid(Unknown Source)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
	at java.base/sun.security.provider.certpath.BasicChecker.check(Unknown Source)
	... 32 more

```

**Comment by oldman20** [comment]
TTS Saver and SHSHHost seem dead
