### ISSUE TITLE
blobs saving issuie

### ISSUE THREAD

**Issue by Xostinaa** [airsquared/blobsaver#683]
java.net.ConnectException: Bad file descriptor
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.Network.makeJsonRequest(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.Utils$LatestVersion.request(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.Utils._checkForUpdates(Unknown Source)
	at airsquared.blobsaver/airsquared.blobsaver.app.Utils.lambda$checkForUpdates$1(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Bad file descriptor
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
Caused by: java.net.SocketException: Bad file descriptor
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	... 5 more

**Comment by Xostinaa** [comment]
[0x359497088601070-2023-06-28T22:57:49Z.txt](https://github.com/user-attachments/files/18099612/0x359497088601070-2023-06-28T22.57.49Z.txt)
[0x359497088601070-2023-06-28T22:57:49Z.txt](https://github.com/user-attachments/files/18099613/0x359497088601070-2023-06-28T22.57.49Z.txt)

**Comment by airsquared** [comment]
No context given, please comment with more information explaining your issue if it is still occurring.
